config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :builds

  root 'welcome#index'

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/build.rb
class Build < ApplicationRecord
	validates :name, presence: true, length: { minimum: 3 }
	validates :country, presence: true, length: { minimum: 2 }
	validates :style, presence: true, length: { minimum: 2 }
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
	
  before_action :authenticate_user!, except: [:index, :show]
	def index
		@builds = Build.page(params[:page]).per(7)
	end
	def show
		@build = Build.find(params[:id])
	end
	def new
    end

  def edit
  	@build = Build.find(params[:id])
  end
   def create
   	
  	@build = Build.new(build_params)
 
    if @build.save
       redirect_to @build
    else
    	render 'new'
  end
end

def update
  @build = Build.find(params[:id])
 
  if @build.update(build_params)
    redirect_to @build
  else
    render 'edit'
  end
end

def destroy
    @build = Build.find(params[:id])
    @build.destroy
 
    redirect_to builds_path
  end
 
  private
  def build_params
    params.require(:build).permit(:name, :country, :style, :photo)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/buildings/new.html.erb
<h1 class="text-center">New Build</h1>
<div class="text-center">

<%= form_for :build, url: buildings_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :country %><br>
    <%= f.text_area :country %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_area :city %>
  </p>

  <p>
    <%= f.label :style %><br>
    <%= f.text_area :style %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>

<% end %>
  </div>

app/views/builds/_form.html.erb
<%= form_for @build do |f| %>
 
  <% if @build.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@build.errors.count, "error") %> prohibited
        this build from being saved:
      </h2>
      <ul>
        <% @build.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <table class="table">
 <div class="text-center">
 <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
 
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_area :country %>
  </div>

  <div class="field">
    <%= f.label :style %><br>
    <%= f.text_area :style %>
  </div>

  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_area :photo %>
  </div>
 
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
  </div>
  </div>
 </table>

<% end %>

app/views/builds/edit.html.erb
<div class="panel panel-success">
<div class="panel-heading"><b>Editing build</b> | <%= link_to 'Back', builds_path %> </div>
 
<%= render 'form' %>

</div>

app/views/builds/index.html.erb
<div class="panel panel-success">
<div class="panel-heading"><b>All builds</b> | <%= link_to 'New build', new_build_path %></div>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th>Style</th>
    <th>Photo</th>
  </tr>
 
  <% @builds.each do |build| %>
    <tr>
      <td><%= build.name %></td>
      <td><%= build.country %></td>
      <td><%= build.style %></td>
      <td><%if build.photo.blank?%>
      <%= image_tag('https://lh3.googleusercontent.com/FOBz3oA4IA6F3Kg9KhAHH3S0UX1ID27IDwSJdz46rCa9QFWcJrMmHDRgxVf48pV3tg=w300', size: '80x80') %>
      <% else %>
      <%= image_tag(build.photo, size:'80x80') %>
      <% end %></td>
      <td><%= link_to 'nfo', build_path(build), class: "btn btn-info fa fa-info" %></td>
      <td><%= link_to 'Edit', edit_build_path(build), class: "btn btn-primary fa fa-cog" %></td>
      <td><%= link_to 'Delete', build_path(build),
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: "btn btn-danger fa fa-trash-o fa-lg" %></td>
    </tr>
  <% end %>
</table>
<%= paginate @builds %>
<%= page_entries_info @builds %>
</div>

app/views/builds/new.html.erb
<div class="panel panel-success">
<div class="panel-heading"><b>New build</b> </div>

<%= form_for :build, url: builds_path do |f| %>

<table class="table">
 <div class="text-center">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
 
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_area :country %>
  </div>

  <div class="field">
    <%= f.label :style %><br>
    <%= f.text_area :style %>
  </div>

  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_area :photo %>
  </div>
 
  <div class="field">
    <%= f.submit %>
  </div>
  </div>
  </table>
<% end %>
</div>

app/views/builds/show.html.erb
<div class="panel panel-success">
<div class="panel-heading"><b>Build</b></div>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th>Style</th>
    <th>Photo</th>
  </tr>
 
 
    <tr>
      <td><%= @build.name %></td>
      <td><%= @build.country %></td>
      <td><%= @build.style %></td>
      <td>
      <%if @build.photo.blank?%>
      <%= image_tag('https://lh3.googleusercontent.com/FOBz3oA4IA6F3Kg9KhAHH3S0UX1ID27IDwSJdz46rCa9QFWcJrMmHDRgxVf48pV3tg=w300', size: '80x80') %>
      <% else %>
      <%= image_tag(@build.photo, size:'80x80') %>
      <% end %>
      </td>
      
    </tr>
  
</table>
</div>

<%= link_to 'Edit', edit_build_path(@build) %> |
<%= link_to 'Back', builds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Architektura</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="navbar navbar-inverse navbar-fixed-top">
        <%= link_to "Architecture", root_path, :class => 'navbar-brand'%>
        <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><%= link_to 'All builds', builds_path %></li>
                </ul>
        
        
        <ul style="margin-right: 8px;margin-top:9px;" class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link glyphicon glyphicon-log-out' %>
        </ul>
        <% end %>
        
</div>
  </div>

  <div class="container modal-content">
    <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="text-center">
<h1 class="fa fa-heart faa-spin fa-2x">Welcome</h1>
<h1> This is the base of buildings, thanks to you can learn more about architecture !</h1>
</div>